startRace(false); setTimeOfDay('paiva'); step(60*4.5);
await TRY('es', async () => { const K = LANDMARKS.find(L => L[0] === 'kauppa'), [W, D] = lmSize(K), [fx, fz] = lloc(K[1], K[2], K[3], -7, D/2 + 15); car.x = fx + 20; car.z = fz; hold(30); const [tx, tz] = lloc(K[1], K[2], K[3], 0, D/2 + 3); await view('es', tx, Y(tx, tz) + 2, tz, fx, Y(fx, fz) + 4.5, fz); });
await TRY('haamu_a', async () => { put(300, 15); hold(2); const fx = Math.sin(car.angle), fz = Math.cos(car.angle), P = { x: car.x + fx*13 - fz*2.4, z: car.z + fz*13 + fx*2.4, a: car.angle }; ghostGroup.visible = true; placeGhost(ghostGroup, P, 1); ghostGroup.visible = true;
  await view('haamu_a', car.x + fx*8, Y(car.x, car.z) + 1, car.z + fz*8, car.x - fx*8 + fz*2.5, Y(car.x, car.z) + 3, car.z - fz*8 - fx*2.5); out.ghostVis = ghostGroup.visible; ghostGroup.visible = false; });
await TRY('hirvi', async () => { const M = HUMANS.filter(q => q.task && q.task.kind === 'moose' && !q.gone); let h = M[0], bc = 1e9; for (const q of M) { const c = treeCount(q.x, q.z, 10); if (c < bc) { bc = c; h = q; } } car.x = h.x + 30; car.z = h.z; hold(30); await aroundClear('hirvi', h.x, h.z, 8, 2.6, 1.5, h.yaw + 1); });
await TRY('jalan', async () => { put(420, 0); hold(5); walkOut(); const h = WALK.h; h.yaw = car.angle; h.x = car.x + Math.sin(car.angle)*3; h.z = car.z + Math.cos(car.angle)*3; keys.ArrowUp = true; for (let k = 0; k < 60*2; k++) { h.yaw = car.angle; hold(1); } keys.ArrowUp = false; hold(10);
  const fx = Math.sin(h.yaw), fz = Math.cos(h.yaw); await view('jalan', h.x, Y(h.x, h.z) + 1.1, h.z, h.x + fx*5 + fz*2, Y(h.x, h.z) + 2, h.z + fz*5 - fx*2); walkIn(true); });
await TRY('maali', async () => { const S = STANDS[0], f = finishLine.position; car.x = S.x + 30; car.z = S.z; hold(60*2); const ang = Math.atan2(f.x - S.x, f.y - S.z); await around('maali', S.x, S.z, 20, 4, ang + 0.35, 2.5); });
await TRY('olymp', async () => { const O = X3.oly; car.x = O.x + 30; car.z = O.z; hold(60*3); await aroundClear('olymp', O.x, O.z, 16, 5, 1, O.yaw + 0.5); });
await TRY('pihat', async () => { const h = HUMANS.find(q => q.task && q.task.kind === 'badminton'); car.x = h.x + 30; car.z = h.z; hold(60*2); await aroundClear('pihat', h.x, h.z, 9, 3, 1.4, 2.2); });
await TRY('porsaat', async () => { const P = tires.filter(t => t.kind === 'pig'); let q = P[0], bc = 1e9; for (const p of P) { const c = treeCount(p.x, p.z, 9); if (c < bc) { bc = c; q = p; } } car.x = q.x + 20; car.z = q.z; hold(10); await aroundClear('porsaat', q.x, q.z, 7, 2.6, 0.4, 0.9); });
await TRY('ufo_b', async () => { const U = UFOS[0]; const gun = HUMANS.find(q => q.propR && q.task && q.task.kind === 'alien' && Math.hypot(q.x - U.x, q.z - U.z) < 15); car.x = gun.x + 22; car.z = gun.z + 4; car.vx = car.vz = 0; UFO_HITS.MAX = 99; hold(60*6);
  for (const B of UFO_BOLTS) if (B.live && Math.hypot(B.x - gun.x, B.z - gun.z) < 6) B.m.visible = false; const a = Math.atan2(car.x - gun.x, car.z - gun.z); await view('ufo_b', gun.x, Y(gun.x, gun.z) + 1, gun.z, gun.x + Math.sin(a + 1.9)*4.2, Y(gun.x, gun.z) + 1.6, gun.z + Math.cos(a + 1.9)*4.2); UFO_HITS.MAX = 3; });
await TRY('tuli_b', async () => { const B = STATIC_LIST.find(b => b.kind === 'house' && !b.station && Math.min(b.hw, b.hl) > 3 && Math.hypot(b.x - car.x, b.z - car.z) > 80 && Math.abs(b.x) < 300 && Math.abs(b.z) < 300 && ambPath(b.x, b.z)); car.x = B.x + 45; car.z = B.z; car.vx = car.vz = 0;
  startFire({ house: B }); B.fire.level = 0.85; let v = null; for (let k = 0; k < 60*150; k++) { hold(1); v = VEHICLES.find(o => o.kind === 'fire' && o.job && o.job.phase === 'spray' && o.job.t > 3); if (v) break; }
  if (!v) { out.tuli_b = 'no engine'; return; } const f = VEHICLES.find(o => o.kind === 'fire'), fm = HUMANS.find(h => h.task && h.task.kind === 'firefighter' && !h.inside) || f; const ang = Math.atan2(fm.x - B.x, fm.z - B.z);
  await view('tuli_b', (B.x + fm.x)/2, Y(B.x, B.z) + 2, (B.z + fm.z)/2, fm.x + Math.sin(ang + 0.9)*9, Y(fm.x, fm.z) + 4, fm.z + Math.cos(ang + 0.9)*9); });
return out;
